services:
  backend:
    build: ./backend
    ports:
      - "443:8080"
    volumes:
      - ./backend/src:/app
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    environment:
      - PYTHONUNBUFFERED=1
      - UI_WEBSOCKET_NAME=${UI_WEBSOCKET_NAME}
      - ROBOT_WEBSOCKET_NAME=${ROBOT_WEBSOCKET_NAME}
  frontend:
    build: ./frontend
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    environment:
      - VITE_UI_WEBSOCKET_NAME=${UI_WEBSOCKET_NAME}
  media:
    build: ./media
    ports:
      - "8554:8554/tcp"
      - "8554:8554/udp"
      - "8889:8889"
      - "8889:8889/udp"
      - "8189:8189/udp"
      - "8189:8189/tcp"
      - "8000:8000/udp"
      - "8000:8000/tcp"
      - "8001:8001/udp"
      - "8001:8001/tcp"
      - "5000:5000"
  surgical_system:
    build: ./surgical_system
    environment:
      - MOCK_ROBOT=1
      - PYTHONUNBUFFERED=1
      - ROBOT_WEBSOCKET_NAME=${ROBOT_WEBSOCKET_NAME}
    depends_on:
      - backend
      - frontend
      - media
    profiles:
      - "mock_robot"
