services:
  backend:
    build: ./backend
    ports:
      - "443:8080"
    volumes:
      - ./backend/src:/app
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
  media:
    build: ./media
    ports:
      - "8554:8554"
      - "8889:8889"
      - "8189:8189/udp"
  surgical_system:
    build: ./surgical_system
    environment:
      - MOCK_ROBOT=true
    depends_on:
      - backend
      - frontend