webrtcIpsFromInterfaces: yes
webrtcIpsFromInterfacesList:
  - wlp3s0
webrtcAdditionalHosts:
  - 130.215.124.84
  - localhost
  - media
pathDefaults:
  source: publisher
  rtspTransport: udp
paths:
  mystream:
    source: publisher
    rtspTransport: udp
