writeQueueSize: 1024
webrtcIpsFromInterfaces: no
webrtcIpsFromInterfacesList:
  - wlp3s0
webrtcAdditionalHosts:
  - 130.215.124.84
  - localhost
rtsp: yes
rtspTransports: [tcp, udp]
rtspEncryption: "no"
# Address of the UDP/RTP listener. This is needed only when "udp" is in protocols.
rtpAddress: :8000
# Address of the UDP/RTCP listener. This is needed only when "udp" is in protocols.
rtcpAddress: :8001
paths:
  mystream:
    source: publisher
    rtspTransport: udp
